config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  filter :locale
  devise_for :users, path: "auth", controllers: {sessions: "sessions"},
    path_names: {sign_in: "login", sign_out: "logout"}

  namespace :admin do
    root "dashboard#index"
    resources :course_masters
    resources :courses do
      resources :subjects, only: :show
      resource :assign_trainers, only: [:edit, :update]
      resource :assign_trainees, only: [:edit, :update]
      resource :change_status_courses, only: :update
      resources :course_subjects, except: :new
      resources :clone_courses, only: :create
    end
    resources :roles do
      resource :allocate_permissions
    end
    resources :subjects do
      resources :task_masters, only: :index
    end
    resources :course_subjects do
      resources :user_subjects, only: :update
      resources :tasks, except: :show
    end
    resources :users do
      resource :evaluations
    end

    resources :evaluations, only: :index

    patch "status_subject/:course_subject_id/:status" => "status_subjects#update",
      as: :status_subject
    resources :evaluation_templates
    resources :ranks
    resources :universities, except: :show
    resources :programming_languages, except: :show
    resources :statuses, except: :show
    resources :user_types, except: :show
    resources :profiles
    resources :notes, except: :index
    resources :locations
    resources :feed_backs, only: :index
    resources :organization_charts, only: :index
    resources :training_managements, only: :index
  end

  namespace :trainer do
    root "dashboard#index"
    resources :course_masters
    resources :courses do
      resources :subjects, only: :show
      resource :assign_trainers, only: [:edit, :update]
      resource :assign_trainees, only: [:edit, :update]
      resource :change_status_courses, only: :update
      resources :course_subjects, except: :new
      resources :clone_courses, only: :create
    end
    resources :subjects do
      resources :task_masters, only: :index
    end
    resources :users do
      resource :evaluations
    end
    resources :feed_backs, only: :index

    resources :course_subjects do
      resources :user_subjects, only: :update
      resources :tasks, except: :show
    end
    resources :roles do
      resource :allocate_permissions
    end

    patch "status_subject/:course_subject_id/:status" => "status_subjects#update",
      as: :status_subject
    resources :evaluations, only: :index
    resources :evaluation_templates
    resources :ranks
    resources :notes, except: :index
    resources :universities, except: :show
    resources :statuses, except: :show
    resources :user_types, except: :show
    resources :locations
    resources :organization_charts, only: :index
    resources :training_managements, only: :index
  end

  root "static_pages#home"

  resources :courses, only: [:show, :index] do
    resources :subjects, only: [:show]
  end

  resources :course_subjects
  resources :users, only: [:edit, :update, :show] do
    resource :profiles
  end

  resources :user_courses, only: [:show] do
    resources :subjects, only: [:show]
  end

  resources :chats, only: :index
  resources :messages, except: [:index, :show, :edit]
  resources :read_marks, only: :update
  resources :tasks, except: [:new, :edit]
  resources :user_subjects, only: :update
  resources :user_tasks, only: :update
  resources :notifications, only: :index
  patch "update_notifications" => "notifications#update"
  resources :feed_backs, only: :create
end

app/models/university.rb
class University < ApplicationRecord
  acts_as_paranoid

  ATTRIBUTES_PARAMS = [:name]

  has_many :profiles

  validates :name, presence: true
end

app/controllers/admin/universities_controller.rb
class Admin::UniversitiesController < ApplicationController
  load_and_authorize_resource except: :show

  def index
    @university = University.new
    add_breadcrumb_index "universities"
    respond_to do |format|
      format.html
      format.json {
        render json: UniversitiesDatatable.new(view_context, @namespace)
      }
    end
  end

  def new
    add_breadcrumb_path "universities"
    add_breadcrumb_new "universities"
  end

  def create
    respond_to do |format|
      if @university.save
        flash.now[:success] = flash_message "created"
        format.html {redirect_to admin_universities_path}
      else
        flash.now[:failed] = flash_message "not_created"
        format.html {render :new}
      end
      format.js
    end
  end

  def edit
    add_breadcrumb_path "universities"
    add_breadcrumb @university.name
    add_breadcrumb_edit "universities"
  end

  def update
    if @university.update_attributes university_params
      flash[:success] = flash_message "updated"
      redirect_to admin_universities_path
    else
      flash_message[:failed] = flash_message "not_updated"
      render :edit
    end
  end

  def destroy
    if @university.destroy
      flash[:success] = flash_message "deleted"
    else
      flash[:failed] = flash_message "not_deleted"
    end
    redirect_to :back
  end

  private
  def university_params
    params.require(:university).permit University::ATTRIBUTES_PARAMS
  end
end

app/controllers/trainer/universities_controller.rb
class Trainer::UniversitiesController < ApplicationController
  load_and_authorize_resource except: :show

  def index
    @university = University.new
    add_breadcrumb_index "universities"
    respond_to do |format|
      format.html
      format.json {
        render json: UniversitiesDatatable.new(view_context, @namespace)
      }
    end
  end

  def new
    add_breadcrumb_path "universities"
    add_breadcrumb_new "universities"
  end

  def create
    respond_to do |format|
      if @university.save
        flash.now[:success] = flash_message "created"
        format.html {redirect_to trainer_universities_path}
      else
        flash.now[:failed] = flash_message "not_created"
        format.html {render :new}
      end
      format.js
    end
  end

  def edit
    add_breadcrumb_path "universities"
    add_breadcrumb @university.name
    add_breadcrumb_edit "universities"
  end

  def update
    if @university.update_attributes university_params
      flash[:success] = flash_message "updated"
      redirect_to trainer_universities_path
    else
      flash_message[:failed] = flash_message "not_updated"
      render :edit
    end
  end

  def destroy
    if @university.destroy
      flash[:success] = flash_message "deleted"
    else
      flash[:failed] = flash_message "not_deleted"
    end
    redirect_to :back
  end

  private
  def university_params
    params.require(:university).permit University::ATTRIBUTES_PARAMS
  end
end

app/views/admin/universities/_form.html.erb
<%= form_for [:admin, @university] do |f| %>
  <div class="row">
    <%= render "shared/error_messages", object: @university %>
    <div class="col-md-8">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", required: true %><br>
      <div class="pull-right">
        <%= f.submit (f.object.new_record? ? t("buttons.create")
          : t("buttons.update")), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/universities/create.js.erb
<% if @university.errors.any? %>
  $(".errors").html("<%= j render "shared/error_messages", object: @university %>");
<% else %>
  $("#user_profile_attributes_university_id").append($("<option></option>")
    .attr("value", <%= @university.id %>)
    .text("<%= @university.name %>")
    .prop("selected", true));
  $("#university-modal").modal("hide");
  $(".flash").html("<%= j render "layouts/flash" %>");
<% end %>

app/views/admin/universities/edit.html.erb
<div class="title profile-active"><%= @university.name %></div>
<%= render "form" %>

app/views/admin/universities/index.html.erb
<div id="universities" class="systems-active">
  <div class="row">
    <div class="col-md-12 title">
      <span>
        <%= link_to t("buttons.new"),
            new_admin_university_path, class: "btn btn-success pull-right" %>
      </span>
    </div>
  </div>
  <table id="university-tbl" class="table table-bordered display"
    data-source="<%= admin_universities_url(format: "json") %>">
      <thead>
        <tr class="active">
          <th></th>
          <th class="name"><%= t "table.thead.name" %></th>
          <th class="action"></th>
          <th class="action"></th>
        </tr>
      </thead>
      <tbody>
      </tbody>
  </table>
</div>

app/views/admin/universities/new.html.erb
<div id="universities" class="profile-active">
  <div class="row">
    <div class="col-md-8">
      <%= render "form" %>
    </div>
  </div>
</div>