config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  filter :locale
  devise_for :users, path: "auth", controllers: {sessions: "sessions"},
    path_names: {sign_in: "login", sign_out: "logout"}

  namespace :admin do
    root "dashboard#index"
    resources :course_masters
    resources :courses do
      resources :subjects, only: :show
      resource :assign_trainers, only: [:edit, :update]
      resource :assign_trainees, only: [:edit, :update]
      resource :change_status_courses, only: :update
      resources :course_subjects, except: :new
      resources :clone_courses, only: :create
    end
    resources :roles do
      resource :allocate_permissions
    end
    resources :subjects do
      resources :task_masters, only: :index
    end
    resources :course_subjects do
      resources :user_subjects, only: :update
      resources :tasks, except: :show
    end
    resources :users do
      resource :evaluations
    end

    resources :evaluations, only: :index

    patch "status_subject/:course_subject_id/:status" => "status_subjects#update",
      as: :status_subject
    resources :evaluation_templates
    resources :ranks
    resources :universities, except: :show
    resources :programming_languages, except: :show
    resources :statuses, except: :show
    resources :user_types, except: :show
    resources :profiles
    resources :notes, except: :index
    resources :locations
    resources :feed_backs, only: :index
    resources :organization_charts, only: :index
    resources :training_managements, only: :index
  end

  namespace :trainer do
    root "dashboard#index"
    resources :course_masters
    resources :courses do
      resources :subjects, only: :show
      resource :assign_trainers, only: [:edit, :update]
      resource :assign_trainees, only: [:edit, :update]
      resource :change_status_courses, only: :update
      resources :course_subjects, except: :new
      resources :clone_courses, only: :create
    end
    resources :subjects do
      resources :task_masters, only: :index
    end
    resources :users do
      resource :evaluations
    end
    resources :feed_backs, only: :index

    resources :course_subjects do
      resources :user_subjects, only: :update
      resources :tasks, except: :show
    end
    resources :roles do
      resource :allocate_permissions
    end

    patch "status_subject/:course_subject_id/:status" => "status_subjects#update",
      as: :status_subject
    resources :evaluations, only: :index
    resources :evaluation_templates
    resources :ranks
    resources :notes, except: :index
    resources :universities, except: :show
    resources :statuses, except: :show
    resources :user_types, except: :show
    resources :locations
    resources :organization_charts, only: :index
    resources :training_managements, only: :index
  end

  root "static_pages#home"

  resources :courses, only: [:show, :index] do
    resources :subjects, only: [:show]
  end

  resources :course_subjects
  resources :users, only: [:edit, :update, :show] do
    resource :profiles
  end

  resources :user_courses, only: [:show] do
    resources :subjects, only: [:show]
  end

  resources :chats, only: :index
  resources :messages, except: [:index, :show, :edit]
  resources :read_marks, only: :update
  resources :tasks, except: [:new, :edit]
  resources :user_subjects, only: :update
  resources :user_tasks, only: :update
  resources :notifications, only: :index
  patch "update_notifications" => "notifications#update"
  resources :feed_backs, only: :create
end

app/models/location.rb
class Location < ApplicationRecord
  acts_as_paranoid

  belongs_to :manager, class_name: User.name, foreign_key: :user_id

  has_many :profiles
  has_many :courses

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :manager, presence: true, uniqueness: {case_sensitive: false}

  after_save :update_user_location

  delegate :name, to: :manager, prefix: true, allow_nil: true

  private
  def update_user_location
    manager_profile = Profile.find_or_initialize_by user_id: manager.id
    manager_profile.location_id = id
    manager_profile.save
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  load_and_authorize_resource
  skip_load_resource only: :show
  before_action :find_location, only: :show
  before_action :load_managers, except: :destroy
  before_action :set_breadcrumb_new, only: [:new, :create]
  before_action :set_breadcrumb_edit, only: [:edit, :update]

  def index
    respond_to do |format|
      format.html {add_breadcrumb_index "locations"}
      format.json {
        render json: LocationsDatatable.new(view_context, @namespace)
      }
    end
  end

  def show
    @manager = @location.manager
    @trainers = User.trainers.includes(:trainees).by_location @location.id

    add_breadcrumb_path "locations"
    add_breadcrumb @location.name
  end

  def new
  end

  def create
    respond_to do |format|
      if @location.save
        flash.now[:success] = flash_message "created"
        format.html {redirect_to admin_locations_path}
      else
        flash.now[:failed] = flash_message "not_created"
        format.html {render :new}
      end
      format.js
    end
  end

  def edit
  end

  def update
    if @location.update_attributes location_params
      flash[:success] = flash_message "created"
      redirect_to admin_locations_path
    else
      flash[:failed] = flash_message "not_created"
      render :edit
    end
  end

  def destroy
    if @location.destroy
      flash[:success] = flash_message "deleted"
    else
      flash[:failed] = flash_message "not_deleted"
    end
    redirect_to admin_locations_path
  end

  private
  def location_params
    params.require(:location).permit :name, :user_id
  end

  def load_managers
    @managers = User.not_trainees
  end

  def set_breadcrumb_new
    add_breadcrumb_path "locations"
    add_breadcrumb_new "locations"
  end

  def set_breadcrumb_edit
    add_breadcrumb_path "locations"
    add_breadcrumb @location.name
    add_breadcrumb_edit "locations"
  end

  def find_location
    @location = Location.includes(:manager).find_by_id params[:id]
    unless @location
      redirect_to admin_locations_path
      flash[:alert] = flash_message "not_find"
    end
  end
end

app/controllers/trainer/locations_controller.rb
class Trainer::LocationsController < ApplicationController
  load_and_authorize_resource
  before_action :load_managers, except: :destroy
  before_action :set_breadcrumb_new, only: [:new, :create]
  before_action :set_breadcrumb_edit, only: [:edit, :update]

  def index
    respond_to do |format|
      format.html {add_breadcrumb_index "locations"}
      format.json {
        render json: LocationsDatatable.new(view_context, @namespace)
      }
    end
  end

  def show
    @manager = @location.manager
    @trainers = User.trainers.by_location @location.id

    add_breadcrumb_path "locations"
    add_breadcrumb @location.name
  end

  def new
  end

  def create
    respond_to do |format|
      if @location.save
        flash.now[:success] = flash_message "created"
        format.html {redirect_to trainer_locations_path}
      else
        flash.now[:failed] = flash_message "not_created"
        format.html {render :new}
      end
      format.js
    end
  end

  def edit
  end

  def update
    if @location.update_attributes location_params
      flash[:success] = flash_message "created"
      redirect_to trainer_locations_path
    else
      flash[:failed] = flash_message "not_created"
      render :edit
    end
  end

  def destroy
    if @location.destroy
      flash[:success] = flash_message "deleted"
    else
      flash[:failed] = flash_message "not_deleted"
    end
    redirect_to trainer_locations_path
  end

  private
  def location_params
    params.require(:location).permit :name, :user_id
  end

  def load_managers
    @managers = User.not_trainees
  end

  def set_breadcrumb_new
    add_breadcrumb_path "locations"
    add_breadcrumb_new "locations"
  end

  def set_breadcrumb_edit
    add_breadcrumb_path "locations"
    add_breadcrumb @location.name
    add_breadcrumb_edit "locations"
  end
end

app/views/admin/locations/_form.html.erb
<div id="locations-form" class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @location] do |f| %>
      <%= render "shared/error_messages", object: @location %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", required: true,
        placeholder: t("locations.form.input_location_name") %>

      <%= f.label :user_id %>
      <%= f.select :user_id, @managers.collect{|u| [u.name, u.id]}, {},
        {selected: f.object.user_id, class: "form-control"} %>

      <br />
      <div class="pull-right">
        <%= f.submit (f.object.new_record? ? t("button.create")
          : t("buttons.save")), class: "btn btn-primary text-right" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/locations/_trainee.html.erb
<tr>
  <td class="trainee-image"><%= link_to avatar_user_tag(trainee, "img-circle",
    Settings.image_size_30), trainee, title: trainee.name %></td>
  <td><%= link_to trainee.name, trainee %></td>
</tr>

app/views/admin/locations/_trainer.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="trainee-image"><%= link_to avatar_user_tag(trainer, "img-circle",
        Settings.image_size_30), trainer, title: trainer.name %></th>
      <th><%= link_to trainer.name, trainer %></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "trainee", collection: trainer.trainees, as: :trainee %>
  </tbody>
</table>

app/views/admin/locations/create.js.erb
<% if @location.errors.any? %>
  $(".errors").html("<%= j render "shared/error_messages", object: @location %>");
<% else %>
  $("#user_profile_attributes_location_id").append($("<option></option>")
    .attr("value", <%= @location.id %>)
    .text("<%= @location.name %>")
    .prop("selected", true));
  $("#location-modal").modal("hide");
  $(".flash").html("<%= j render "layouts/flash" %>");
<% end %>

app/views/admin/locations/edit.html.erb
<%= render "form" %>

app/views/admin/locations/index.html.erb
<div id="list-locations" class="row systems-active">
  <div class="col-md-12">
    <div class="title">
      <span class="pull-right">
        <%= link_to t("locations.buttons.admin.new"),
          new_admin_location_path, class: "btn btn-success pull-right" %>
      </span>
    </div>

    <table id="tbl-location" class="table table-bordered"
      data-source="<%= admin_locations_url format: "json" %>">
      <thead>
        <tr class="active">
          <th></th>
          <th><%= t "locations.name" %></th>
          <th><%= t "locations.manager" %></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/locations/new.html.erb
<%= render "form" %>

app/views/admin/locations/show.html.erb
<div id="users-structure">
  <div class="manager-info">
    <div class="manager">
      <%= link_to avatar_user_tag(@manager, "img-circle",
        Settings.image_size_30), @manager, title: @manager.name,
        class: "manager-image" %>
      <%= link_to @manager.name ,@manager %>
    </div>
  </div>
  <div id="tbl-user-structure">
    <div class="structure-content">
    <%= render partial: "trainer", collection: @trainers, as: :trainer %>
  </div>
  </div>
</div>