config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  filter :locale
  devise_for :users, path: "auth", controllers: {sessions: "sessions"},
    path_names: {sign_in: "login", sign_out: "logout"}

  namespace :admin do
    root "dashboard#index"
    resources :course_masters
    resources :courses do
      resources :subjects, only: :show
      resource :assign_trainers, only: [:edit, :update]
      resource :assign_trainees, only: [:edit, :update]
      resource :change_status_courses, only: :update
      resources :course_subjects, except: :new
      resources :clone_courses, only: :create
    end
    resources :roles do
      resource :allocate_permissions
    end
    resources :subjects do
      resources :task_masters, only: :index
    end
    resources :course_subjects do
      resources :user_subjects, only: :update
      resources :tasks, except: :show
    end
    resources :users do
      resource :evaluations
    end

    resources :evaluations, only: :index

    patch "status_subject/:course_subject_id/:status" => "status_subjects#update",
      as: :status_subject
    resources :evaluation_templates
    resources :ranks
    resources :universities, except: :show
    resources :programming_languages, except: :show
    resources :statuses, except: :show
    resources :user_types, except: :show
    resources :profiles
    resources :notes, except: :index
    resources :locations
    resources :feed_backs, only: :index
    resources :organization_charts, only: :index
    resources :training_managements, only: :index
  end

  namespace :trainer do
    root "dashboard#index"
    resources :course_masters
    resources :courses do
      resources :subjects, only: :show
      resource :assign_trainers, only: [:edit, :update]
      resource :assign_trainees, only: [:edit, :update]
      resource :change_status_courses, only: :update
      resources :course_subjects, except: :new
      resources :clone_courses, only: :create
    end
    resources :subjects do
      resources :task_masters, only: :index
    end
    resources :users do
      resource :evaluations
    end
    resources :feed_backs, only: :index

    resources :course_subjects do
      resources :user_subjects, only: :update
      resources :tasks, except: :show
    end
    resources :roles do
      resource :allocate_permissions
    end

    patch "status_subject/:course_subject_id/:status" => "status_subjects#update",
      as: :status_subject
    resources :evaluations, only: :index
    resources :evaluation_templates
    resources :ranks
    resources :notes, except: :index
    resources :universities, except: :show
    resources :statuses, except: :show
    resources :user_types, except: :show
    resources :locations
    resources :organization_charts, only: :index
    resources :training_managements, only: :index
  end

  root "static_pages#home"

  resources :courses, only: [:show, :index] do
    resources :subjects, only: [:show]
  end

  resources :course_subjects
  resources :users, only: [:edit, :update, :show] do
    resource :profiles
  end

  resources :user_courses, only: [:show] do
    resources :subjects, only: [:show]
  end

  resources :chats, only: :index
  resources :messages, except: [:index, :show, :edit]
  resources :read_marks, only: :update
  resources :tasks, except: [:new, :edit]
  resources :user_subjects, only: :update
  resources :user_tasks, only: :update
  resources :notifications, only: :index
  patch "update_notifications" => "notifications#update"
  resources :feed_backs, only: :create
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  load_and_authorize_resource
  load_and_authorize_resource :course
  skip_load_resource :course, only: :show
  skip_load_resource only: [:edit, :update]
  before_action :find_subject_in_edit, only: [:edit, :update]
  before_action :find_course_in_show, only: :show

  def index
    @subject = Subject.new
    respond_to do |format|
      format.html {add_breadcrumb_index "subjects"}
      format.json {
        render json: SubjectsDatatable.new(view_context, @namespace)
      }
    end
  end

  def show
    @course_subject = @course.course_subjects.find do |course_subject|
      course_subject.subject_id == @subject.id
    end
    @user_subjects = @course_subject.user_subjects
    @user_subjects_not_finishs = @user_subjects.not_finish @user_subjects.finish

    add_breadcrumb_path "courses"
    add_breadcrumb @course.name, admin_course_path(@course)
    add_breadcrumb @course_subject.subject_name
    load_chart_data
  end

  def new
    @subject.documents.build
    @subject.task_masters.build

    add_breadcrumb_path "subjects"
    add_breadcrumb_new "subjects"
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = flash_message "created"
      redirect_to admin_subjects_path
    else
      flash[:failed] = flash_message "not_created"
      render :new
    end
  end

  def edit
    add_breadcrumb_path "subjects"
    add_breadcrumb @subject.name, admin_subject_task_masters_path(@subject)
    add_breadcrumb_edit "subjects"
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = flash_message "updated"
      redirect_to admin_subject_task_masters_path(@subject)
    else
      flash[:failed] = flash_message "not_updated"
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = flash_message "deleted"
    else
      flash.now[:failed] = flash_message "not_deleted"
    end
    respond_to do |format|
      format.html {redirect_to admin_subjects_path}
    end
  end

  private
  def subject_params
    params.require(:subject).permit Subject::SUBJECT_ATTRIBUTES_PARAMS
  end

  def find_subject_in_edit
    @subject = Subject.includes(:documents, :task_masters)
      .find_by_id params[:id]
    redirect_if_object_nil @subject
  end

  def find_course_in_show
    @course = Course.includes(course_subjects: [user_subjects: :user])
      .find_by_id params[:course_id]
    redirect_if_object_nil @course
  end

  def load_chart_data
    if @user_subjects.any?
      @user_tasks_chart_data = {}

      @user_subjects.each do |user_subject|
        @user_tasks_chart_data[user_subject.user.name] = user_subject
          .user_tasks.finished.size
      end
    end
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  load_and_authorize_resource :user
  load_and_authorize_resource :subject, only: :show

  before_action :load_course, only: :update
  before_action :load_user_course, only: :show
  before_action :check_status, only: :update
  before_action :check_status_subject, only: :update

  def show
    @task_masters = @subject.task_masters
    @course_subject = CourseSubject.includes(
      user_subjects: [:course, user_tasks: [:task, :user, :user_subject]])
      .find_by course_id: @user_course.course_id, subject_id: @subject.id

    @user_subjects = @course_subject.user_subjects
    @user_subject = @user_subjects.find{|user_subject| user_subject.user_id == @user_course.user_id}

    @users = @user_subject.course.users
    @trainers = @users.trainers
    @trainees = @users.trainees
    @members = @users.show_members
    @count_member = @users.size - Settings.number_member_show

    @user_tasks = @user_subject.user_tasks
    @number_of_task = @user_tasks.size

    @task_statuses = UserTask.statuses
    @task_statuses.each do |key, value|
      instance_variable_set "@number_of_task_#{key}", @user_tasks.send(key).size
    end

    @task = Task.new
    @task.user_tasks.build

    load_chart_data
  end

  private
  def load_course
    @user_subject = UserSubject.find params[:subject_id]
    @user_course = @user_subject.user_course
  end

  def check_status
    redirect_to :back unless params[:status] == Settings.finish
  end

  def check_status_subject
    redirect_to :back unless @user_subject.progress?
  end

  def load_user_course
    @user_course = UserCourse.includes(:user).find_by_id params[:user_course_id]
  end

  def load_chart_data
    unless @user_subject.init?
      @user_tasks_chart_data = {}

      @user_subjects.includes(:user, :user_course).each do |user_subject|
        @user_tasks_chart_data[user_subject.user.name] = user_subject.user_tasks.finished.size
      end
    end
  end
end

app/controllers/trainer/assign_trainees_controller.rb
class Trainer::AssignTraineesController < ApplicationController
  load_and_authorize_resource :course
  authorize_resource class: false

  def edit
    @supports = Supports::Course.new @course

    add_breadcrumb_path "courses"
    add_breadcrumb @course.name, trainer_course_path(@course)
    add_breadcrumb t "courses.assign_trainees"
  end

  def update
    if params[:course] && @course.update_attributes(course_params)
      ExpectedTrainingDateService.new(@course).expected_training_end_date
      flash[:success] = flash_message "updated"
    else
      flash[:danger] = flash_message "not_updated"
    end
    redirect_to trainer_course_path @course
  end

  private
  def course_params
    params.require(:course).permit Course::USER_COURSE_ATTRIBUTES_PARAMS
  end
end

app/controllers/trainer/assign_trainers_controller.rb
class Trainer::AssignTrainersController < ApplicationController
  authorize_resource :course, class: false
  before_action :find_course

  def edit
   @supports = Supports::Course.new @course

    add_breadcrumb_path "courses"
    add_breadcrumb @course.name, trainer_course_path(@course)
    add_breadcrumb t "courses.assign_trainers"
  end

  def update
    if params[:course] && @course.update_attributes(course_params)
      flash[:success] = flash_message "updated"
    else
      flash[:danger] = flash_message "not_updated"
    end
    redirect_to trainer_course_path @course
  end

  private
  def course_params
    params.require(:course).permit Course::USER_COURSE_ATTRIBUTES_PARAMS
  end

  def find_course
    @course = Course.includes(:user_courses).find_by_id params[:course_id]
    if @course.nil?
      flash[:alert] = flash_message "not_find"
      redirect_to trainer_courses_path
    end
  end
end

app/controllers/trainer/change_status_courses_controller.rb
class Trainer::ChangeStatusCoursesController < ApplicationController
  load_and_authorize_resource :course
  authorize_resource class: false

  def update
    if @course.init?
      @course.start_course current_user
      key = Notification.keys[:start]
      flash[:success] = flash_message "start_course"
    elsif @course.progress?
      key = Notification.keys[:finish]
      @course.finish_course current_user
      flash[:success] = flash_message "finish_course"
    elsif @course.finish?
      key = Notification.keys[:reopen]
      @course.reopen_course current_user
      flash[:success] = flash_message "reopen_course"
    else
      flash[:failed] = flash_message "course_not_upate"
    end
    CourseNotificationBroadCastJob.perform_now @course, key, current_user.id
    redirect_to trainer_course_path @course
  end
end

app/controllers/trainer/clone_courses_controller.rb
class Trainer::CloneCoursesController < ApplicationController
  load_and_authorize_resource :course
  authorize_resource class: false

  def create
    clone_course_service = CloneCourseService.new @course
    @clone_course = clone_course_service.clone_course
    if @clone_course
      flash[:success] = t "courses.confirms.clone_success"
      redirect_to [:trainer, @clone_course]
    else
      flash[:failed] = t "courses.confirms.not_clone"
      redirect_to trainer_courses_path
    end
  end
end

app/controllers/trainer/course_subjects_controller.rb
class Trainer::CourseSubjectsController < ApplicationController
  load_and_authorize_resource
  load_and_authorize_resource :course
  before_action :load_course, except: :new

  def index
    @course_subjects = @course.course_subjects
  end

  def edit
    add_breadcrumb_path "courses"
    add_breadcrumb @course_subject.course_name, trainer_course_path(@course)
    add_breadcrumb @course_subject.subject_name, trainer_course_subject_path(@course,
      @course_subject.subject)
    add_breadcrumb_edit "subjects"
  end

  def update
    if @course_subject.update_attributes course_subject_params
      respond_to do |format|
        format.js do
          render nothing: true
        end
        format.html do
          flash[:success] = flash_message "updated"
          redirect_to trainer_course_subject_path @course, @course_subject.subject
        end
      end
    else
      flash[:failed] = flash_message "not_updated"
      render :edit
    end
  end

  def destroy
    if @course_subject.destroy
      flash[:success] = flash_message "deleted"
    else
      flash[:failed] = flash_message "not_deleted"
    end
    redirect_to trainer_course_path @course
  end

  private
  def course_subject_params
    params.require(:course_subject).permit CourseSubject::ATTRIBUTES_PARAMS
  end

  def load_course
    @course = Course.find_by_id params[:course_id]
    if @course.nil?
      flash[:alert] = flash_message "not_find"
      redirect_to trainer_courses_path
    end
  end
end

app/controllers/trainer/courses_controller.rb
class Trainer::CoursesController < ApplicationController
  load_and_authorize_resource
  skip_load_resource only: [:show, :edit]
  before_action :load_data, except: [:index, :show, :destroy]
  before_action :find_course_in_show, only: :show
  before_action :find_course_in_edit, only: :edit

  def index
    respond_to do |format|
      format.html {add_breadcrumb_index "courses"}
      format.json {
        render json: CoursesDatatable.new(view_context, @namespace)
      }
    end
  end

  def new
    @course.documents.build
    add_breadcrumb_path "courses"
    add_breadcrumb_new "courses"
  end

  def edit
    add_breadcrumb_path "courses"
    add_breadcrumb @course.name, :trainer_course_path
    add_breadcrumb_edit "courses"
  end

  def create
    if @course.save
      flash[:success] = flash_message "created"
      redirect_to trainer_courses_path
    else
      flash[:failed] = flash_message "not_created"
      render :new
    end
  end

  def update
    if @course.update_attributes course_params
      flash[:success] = flash_message "updated"
      redirect_to trainer_course_path(@course)
    else
      flash[:failed] = flash_message "not_updated"
      render :edit
    end
  end

  def show
    @supports = Supports::Course.new @course
    add_breadcrumb_path "courses"
    add_breadcrumb @course.name, :trainer_course_path
  end

  def destroy
    if @course.destroy
      flash[:success] = flash_message "deleted"
    else
      flash[:failed] = flash_message "not_deleted"
    end
    redirect_to trainer_courses_path
  end

  private
  def course_params
    params.require(:course).permit Course::COURSE_ATTRIBUTES_PARAMS
  end

  def load_data
    @subjects = Subject.all
    @programming_languages = ProgrammingLanguage.all
    @locations = Location.all
  end

  def find_course_in_show
    @course = Course.includes(:programming_language).find_by_id params[:id]
    redirect_if_object_nil @course
  end

  def find_course_in_edit
    @course = Course.includes(:documents).find_by_id params[:id]
    redirect_if_object_nil @course
  end
end

app/controllers/trainer/dashboard_controller.rb
class Trainer::DashboardController < ApplicationController
  before_action :check_access, only: :index

  def index
    load_chart_data
    add_breadcrumb_index "dashboard"
  end

  private
  def load_chart_data
    @start_date = Date.today - Settings.number_day_of_user_chart.day
    @end_date = Date.today
    load_user_sign_up_in_day
    load_course_new_in_day
    load_course_finished_in_day
  end

  def load_user_sign_up_in_day
    @user_sign_up_chart_data = {}
    @users = User.created_between @start_date, @end_date
    @user_sign_up_chart_data = get_data @users, @user_sign_up_chart_data
  end

  def load_course_new_in_day
    @new_course_chart_data = {}
    @courses = Course.created_between @start_date, @end_date
    @new_course_chart_data = get_data @courses, @new_course_chart_data
  end

  def load_course_finished_in_day
    @finished_course_chart_data = {}
    @courses_finished = Course.finished_between @start_date, @end_date
    @finished_course_chart_data = get_data @courses_finished,
      @finished_course_chart_data
  end

  def get_data datas, hash
    (@start_date..@end_date).each do |date|
      datas.each do |data|
        if data.created_at.to_date == date && hash[date]
          hash[date] += 1
        elsif data.created_at.to_date == date
          hash[date] = 1
        elsif hash[date].nil?
          hash[date] = 0
        end
      end
    end
    hash = hash.map {|key, value| [key.to_s, value]}
  end

  def check_access
    unless current_user.is_trainer?
      flash[:alert] = t "error.not_authorize"
      redirect_to root_path
    end
  end
end

app/controllers/trainer/feed_backs_controller.rb
class Trainer::FeedBacksController < ApplicationController
  load_and_authorize_resource

  def index
    @feed_backs = FeedBack.order_by_time
    add_breadcrumb_index "feed_backs"
  end
end

app/controllers/trainer/organization_charts_controller.rb
class Trainer::OrganizationChartsController < ApplicationController
  before_action :verify_trainer

  def index
    @locations = Location.includes :manager

    add_breadcrumb_index "organization_charts"
  end

  private
  include VerifyTrainer
end

app/views/trainer/subjects/_document_fields.html.erb
<div class="row document-field">
  <div class="col-md-6">
    <%= f.text_field :name, placeholder: t("subjects.document_name"),
      class: "form-control" %>
  </div>
  <div class="col-md-5">
    <% unless f.object.new_record? %>
      <i>
        <%= f.label t("subjects.document_url") %>
        <%= link_to f.object.name, f.object.content.url, target: "_blank" %>
      </i>
    <% end %>
    <%= f.file_field :content %><br>
  </div>
  <div class="col-md-1">
    <%= link_to_remove_fields t("subjects.document_remove"), f %>
  </div>
</div>

app/views/trainer/subjects/_form.html.erb
<div id="subjects-form">
  <%= form_for [:trainer, @subject] do |f| %>
    <div class="row">
      <%= render "shared/error_messages", object: @subject %>
      <div class="title"><%= @subject.name %></div>
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-2 text-right">
            <span><%= t "subjects.fields.name" %>:</span>
          </div>
          <div class="col-md-9">
            <%= f.text_field :name, class: "form-control", required: true,
              placeholder: I18n.t("subjects.form.input_subject_name") %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-2 text-right">
            <span><%= t "subjects.image" %>:</span>
          </div>
          <div class="col-md-9">
            <%= f.file_field :image, class: "form-control" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-2 text-right">
            <span><%= t "subjects.description" %>:</span>
          </div>
          <div class="col-md-9">
            <%= f.text_area :description, class: "form-control",
              placeholder: I18n.t("subjects.form.input_subject_description") %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-2 text-right">
            <span><%= t "subjects.content" %></span>
          </div>
          <div class="col-md-9">
            <%= f.text_area :content, class: "ckeditor-field form-control" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-2 text-right">
            <span><%= t "subjects.during_time" %>:</span>
          </div>
          <div class="col-md-9">
            <%= f.number_field :during_time, class: "form-control", required: true,
              placeholder: I18n.t("subjects.form.input_subject_during_time") %>
          </div>
        </div>
        <br>
      </div>
    </div><br>
    <div class="row">
      <div class="col-md-2 text-right"><%= t "subjects.document" %></div>
      <div class="col-md-9">
        <%= f.fields_for :documents do |builder| %>
          <%= render "document_fields", f: builder %>
        <% end %>
        <strong><%= link_to_add_fields t("subjects.document"), f, :documents %></strong>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-2 col-md-offset-6">
        <h3><%= t "subjects.task.list_tasks" %></h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= f.fields_for :task_masters do |builder| %>
          <%= render "task_master_fields", f: builder %>
        <% end %>
        <span id="add-task-masters">
          <%= link_to_add_fields t("subjects.dynamic_form.add"), f, :task_masters %>
        </span>
      </div>
    </div>

    <div class="row">
      <div class="col-md-1 col-md-offset-10">
        <%= f.submit (f.object.new_record? ? t("button.create")
          : t("button.save")), class: "btn btn-primary text-right" %>
      </div>
    </div>
  <% end %>
</div>

app/views/trainer/subjects/_subject_info.html.erb
<div class="row">
  <div class="col-md-2">
    <%= set_image @course_subject %>
  </div>
  <div class="col-md-5">
    <h2 id="subject-h2-header">
      <span id="subject-header"><%= @course_subject.subject_name %></span>
    </h2>
    <div>
      <i><%= @course_subject.subject_description %></i>
    </div>
    <p class="working-days">
      <%= "#{t "subjects.fields.during_time"}:
        #{@subject.during_time} #{t "subjects.fields.days"}" %>
    </p>
  </div>
  <div class="box-divider col-md-4">
    <div class="label-title"><%= t "user_tasks.description" %></div>
    <p><%= @course_subject.subject_content.html_safe if @course_subject.subject_content %></p>
  </div>
  <div class="col-md-1">
    <%= render "shared/action_user_subjects" %>
  </div>
</div>
<% if data_finish_task @user_tasks_chart_data %>
  <div id="user-subjects-charts"
    data-user-name="<%= @user_tasks_chart_data.keys %>"
    data-total-number-tasks="<%= @user_tasks_chart_data.values %>">
  </div>
<% end %>
<br>

app/views/trainer/subjects/_task_master_fields.html.erb
<div class="row form-new-tasks">
  <div class="col-md-11 new-task-master">
    <div class="row">
      <div class="col-md-2 text-right">
        <span><%= t "tasks.fields.name" %>:</span>
      </div>
      <div class="col-md-10">
        <%= f.text_field :name, class: "form-control",
          placeholder: t("tasks.form.input_task_name") %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-2 text-right">
        <span><%= t "tasks.description" %>:</span>
      </div>
      <div class="col-md-10">
        <%= f.text_area :description, class: "form-control",
          placeholder: t("tasks.form.input_task_description") %>
      </div>
    </div>
  </div>
  <div class="col-md-1">
    <%= link_to_remove_fields t("subjects.dynamic_form.remove"), f %>
  </div>
</div>
<br>

app/views/trainer/subjects/_user_lists.html.erb
<table class="user-task-info table">
  <thead>
    <tr>
      <th class="col-sm-3"><%= t "subjects.fields.name" %></th>
      <th class="col-sm-2"><%= t "subjects.fields.start_date" %></th>
      <th class="col-sm-2"><%= t "subjects.fields.end_date" %></th>
      <th class="col-sm-1"><%= t "subjects.fields.status" %></th>
      <th class="col-sm-2"><%= t "subjects.fields.progress" %></th>
      <th class="col-sm-2 action"><%= t "subjects.fields.action" %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @user_subjects %>
  </tbody>
</table>

app/views/trainer/subjects/create.js.erb
<% unless @subject.id.nil? %>
  $("#subject_section").
    append("<%= escape_javascript(render "subject", subject: @subject) %>");
<% end %>
$("#flash").children().remove();
$("#flash").prepend("<%= j render partial: "shared/flash_banner" %>");
$("#show_flash").fadeOut(1000);

app/views/trainer/subjects/edit.html.erb
<div class=" title text-center"><%= t "subjects.edit_subject"%></div>
<%= render "form" %>

app/views/trainer/subjects/index.html.erb
<div id="list-subjects">
  <div class="row">
    <div class="col-md-12 title">
      <span>
        <%= link_to t("subjects.buttons.trainer.new"),
          new_trainer_subject_path, class: "btn btn-success pull-right" %>
      </span>
    </div>
  </div>
  <table id="subjects" class="table table-bordered display" data-source="<%= trainer_subjects_url(format: "json") %>" >
    <thead>
      <tr class="active">
        <th></th>
        <th class="subject-name"><%= t "subjects.fields.name" %></th>
        <th><%= t "subjects.fields.description" %></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/trainer/subjects/new.html.erb
<div class=" title text-center"><%= t "subjects.create_subject"%></div>
<%= render "form" %>

app/views/trainer/subjects/show.html.erb
<div id="user-subject" >
  <div class="row">
    <div class="col-md-12">
      <div class="user-lists">
        <%= render "trainer/subjects/subject_info" %>
        <%= render "user_lists" %>
      </div>
    </div>
  </div>
</div>